algo = input("Digite algo: ")
print("O tipo primitivo do que você digitou é ",(type(algo)))
print('Só tem espaços? ', algo.isspace())
print('É um número? ', algo.isnumeric())
print('É alfabético? ', algo.isalpha())
print('É alfanumérico? ', algo.isalnum())
print('É maiúscula? ', algo.isupper())
print('É minúscula? ', algo.lower())
print('Está capitalizado? ', algo.title())